### PR TITLE
adding new containment correction from regression

### PR DESCRIPTION
**Pull request by zhangzc11**

### CODE REVIEW

**Comment by shervin86** [comment]
Root files and binaries in general should not be put on git

--
Shervin
Da: Zhicai Zhang
Inviato: lunedì 6 giugno 2016 06:15
A: ECALELFS/ECALpro
Rispondi a: ECALELFS/ECALpro
Oggetto: [ECALELFS/ECALpro] adding new containment correction from regression (#11)


________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ECALELFS/ECALpro/pull/11

Commit Summary

  *   Merge pull request #1 from cippy/mytest2
  *   Merge pull request #2 from cippy/mytest2
  *   Merge pull request #3 from ECALELFS/80X
  *   Merge pull request #4 from cippy/mytest2
  *   Merge pull request #5 from ECALELFS/80X
  *   adding new containment corrections
  *   update new regression (remove DeltaR)
  *   update new regression
  *   update new regression
  *   update new regression
  *   update new regression

File Changes

  *   A FillEpsilonPlot/data/new_JOSH_MVA_pi01_Mediumtrain.root<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-0> (0)
  *   A FillEpsilonPlot/data/new_JOSH_MVA_pi01_Mediumtrain_EE.root<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-1> (0)
  *   A FillEpsilonPlot/data/new_JOSH_MVA_pi02_Mediumtrain.root<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-2> (0)
  *   A FillEpsilonPlot/data/new_JOSH_MVA_pi02_Mediumtrain_EE.root<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-3> (0)
  *   M FillEpsilonPlot/interface/FillEpsilonPlot.h<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-4> (14)
  *   M FillEpsilonPlot/src/FillEpsilonPlot.cc<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-5> (157)
  *   A submit/InputList/run272818.list<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-6> (613)
  *   M submit/methods.py<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-7> (25)
  *   M submit/parameters.py<https://github.com/ECALELFS/ECALpro/pull/11/files#diff-8> (17)

Patch Links:

  *   https://github.com/ECALELFS/ECALpro/pull/11.patch
  *   https://github.com/ECALELFS/ECALpro/pull/11.diff

**Comment by zhangzc11** [comment]
I added 4 root files because they have the GBRForests that were obtained from the regression; they are the similar files as the old regression.

**Comment by emanueledimarco** [comment]
@zhangzc11 could you check the conflicts and then update the pull-request?
Possibly also put the ROOT files in a public afs area to be read. @shervin86 is there a common place for these files?
I will merge this PR then

**Comment by shervin86** [comment]
Unfortunately I'm not aware of a way to save the root files in an efficient way.
I would suggest to use the CERNBOX and setup a public link to be used with a wget command to download the files.

**Comment by zhangzc11** [comment]
also i need to resolve the conflicts since this request was made weeks ago and many changes have been made in the central repository since then -- that's also why we need to keep everyone synced as often as possible. Let's close this pull request and make a new one after i solve the conflicts.

**Comment by emanueledimarco** [comment]
@zhangzc11 Thanks. 
In any case from the tests done with this round of ICs the pi0 are not improving the resolution in EB, so we have time to introduce the improvements for the next round. So let's try to merge any update done so far.
Ideally we will just update the ROOT files as soon as the larger pi0 gun is ready (going to ping Marc again)

**Pull request closed without merging**
